### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by GewelsJI** [Robert0812/deepsaldet#11]
```
Downloading...
--2019-05-07 12:51:20--  http://dl.caffe.berkeleyvision.org/caffe_ilsvrc12.tar.gz
Resolving dl.caffe.berkeleyvision.org (dl.caffe.berkeleyvision.org)... 169.229.222.251
Connecting to dl.caffe.berkeleyvision.org (dl.caffe.berkeleyvision.org)|169.229.222.251|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17858008 (17M) [application/octet-stream]
Saving to: ‘caffe_ilsvrc12.tar.gz’

caffe_ilsvrc12.tar.gz                100%[======================================================================>]  17.03M  3.73MB/s    in 5.9s

2019-05-07 12:51:27 (2.90 MB/s) - ‘caffe_ilsvrc12.tar.gz’ saved [17858008/17858008]

Unzipping...
Done.
/home/winDisk/GepengJi/SOD/003-MCDL
Traceback (most recent call last):
  File "predict_stage1.py", line 11, in <module>
    import datum
  File "/home/winDisk/GepengJi/SOD/003-MCDL/datum.py", line 32, in <module>
    options=None),
  File "/home/jigepeng/.conda/envs/caffe-SSAV/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 497, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.
cp: cannot stat '_tmp/smaps_sc/*': No such file or directory
Traceback (most recent call last):
  File "predict_stage2.py", line 11, in <module>
    import datum
  File "/home/winDisk/GepengJi/SOD/003-MCDL/datum.py", line 32, in <module>
    options=None),
  File "/home/jigepeng/.conda/envs/caffe-SSAV/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 497, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.
cp: cannot stat '_tmp/smaps_mc/*': No such file or directory

```

**Comment by JiahangWu** [comment]
Do you have any solution？I’ve also come across this problem.
